import 'dart:convert';

import 'package:flutter/foundation.dart';

/// Status of a protection alert in the local queue / child-facing feed.
///
/// - [queued]: generated by the parent-side protection flow, not yet seen
///   on the child side.
/// - [seen]: surfaced to the child but not explicitly resolved yet.
/// - [resolved]: child has taken action / acknowledged and cleared it.
enum GuardianProtectionAlertStatus { queued, seen, resolved }

@immutable
class GuardianProtectionAlert {
  const GuardianProtectionAlert({
    required this.id,
    required this.type,
    required this.status,
    required this.state,
    required this.createdAt,
    required this.synced,
    this.appLabel,
    this.title,
    this.body,
    this.reason,
    this.amountHint,
    this.recipientHint,
    this.upiIdHint,
  });

  /// Primary key, currently aligned with the native escalation event id.
  final String id;

  /// Event type; for payment protection child alerts this is `child_alert`.
  final String type;

  final GuardianProtectionAlertStatus status;

  /// Protection state at the time of escalation (amber / red / monitoring / inactive).
  final String state;

  /// Creation timestamp in local time.
  final DateTime createdAt;

  /// Whether this event has been successfully pushed to a remote sink.
  final bool synced;

  final String? appLabel;
  final String? title;
  final String? body;
  final String? reason;
  final String? amountHint;
  final String? recipientHint;
  final String? upiIdHint;

  static const String typeChildAlert = 'child_alert';

  bool get isHighRisk => state == 'red';

  bool get isMediumRisk => state == 'amber';

  bool get isQueued => status == GuardianProtectionAlertStatus.queued;

  bool get isResolved => status == GuardianProtectionAlertStatus.resolved;

  GuardianProtectionAlert copyWith({
    GuardianProtectionAlertStatus? status,
    bool? synced,
  }) {
    return GuardianProtectionAlert(
      id: id,
      type: type,
      status: status ?? this.status,
      state: state,
      createdAt: createdAt,
      synced: synced ?? this.synced,
      appLabel: appLabel,
      title: title,
      body: body,
      reason: reason,
      amountHint: amountHint,
      recipientHint: recipientHint,
      upiIdHint: upiIdHint,
    );
  }

  static GuardianProtectionAlertStatus _parseStatus(String? raw) {
    switch (raw) {
      case 'seen':
        return GuardianProtectionAlertStatus.seen;
      case 'resolved':
        return GuardianProtectionAlertStatus.resolved;
      case 'queued':
      default:
        return GuardianProtectionAlertStatus.queued;
    }
  }

  static String _encodeStatus(GuardianProtectionAlertStatus status) {
    switch (status) {
      case GuardianProtectionAlertStatus.queued:
        return 'queued';
      case GuardianProtectionAlertStatus.seen:
        return 'seen';
      case GuardianProtectionAlertStatus.resolved:
        return 'resolved';
    }
  }

  factory GuardianProtectionAlert.fromDbRow(Map<String, Object?> row) {
    final rawPayload = row['payload'] as String? ?? '{}';
    Map<String, dynamic> payload;
    try {
      final decoded = jsonDecode(rawPayload);
      payload = decoded is Map<String, dynamic> ? decoded : <String, dynamic>{};
    } catch (_) {
      payload = <String, dynamic>{};
    }

    final createdAtMs =
        (row['created_at'] as int?) ??
        (payload['createdAt'] as int?) ??
        DateTime.now().millisecondsSinceEpoch;

    final status = _parseStatus(payload['status'] as String?);

    final state = (payload['state'] as String?) ?? 'monitoring';

    String? asString(dynamic value) => value is String ? value : null;

    return GuardianProtectionAlert(
      id: asString(row['id']) ?? asString(payload['eventId']) ?? '',
      type: asString(row['type']) ?? typeChildAlert,
      status: status,
      state: state,
      createdAt: DateTime.fromMillisecondsSinceEpoch(createdAtMs).toLocal(),
      synced: ((row['synced'] as int?) ?? 0) != 0,
      appLabel: asString(payload['appLabel'] ?? payload['app_label']),
      title: asString(payload['title'] ?? payload['reviewTitle']),
      body: asString(payload['body'] ?? payload['reviewBody']),
      reason: asString(payload['reason']),
      amountHint: asString(
        payload['amountHint'] ?? payload['detectedAmountHint'],
      ),
      recipientHint: asString(
        payload['recipientHint'] ?? payload['detectedRecipientHint'],
      ),
      upiIdHint: asString(payload['upiIdHint'] ?? payload['detectedUpiIdHint']),
    );
  }

  factory GuardianProtectionAlert.fromRemoteMap(Map<String, dynamic> data) {
    String? asString(dynamic value) => value is String ? value : null;

    final createdAtMs =
        data['createdAtMs'] as int? ??
        data['created_at_ms'] as int? ??
        DateTime.now().millisecondsSinceEpoch;

    return GuardianProtectionAlert(
      id: asString(data['eventId']) ?? asString(data['id']) ?? '',
      type: asString(data['type']) ?? typeChildAlert,
      status: _parseStatus(asString(data['status'])),
      state: asString(data['state']) ?? 'monitoring',
      createdAt: DateTime.fromMillisecondsSinceEpoch(createdAtMs).toLocal(),
      synced: true,
      appLabel: asString(data['appLabel'] ?? data['app_label']),
      title: asString(data['title'] ?? data['reviewTitle']),
      body: asString(data['body'] ?? data['reviewBody']),
      reason: asString(data['reason']),
      amountHint: asString(data['amountHint'] ?? data['detectedAmountHint']),
      recipientHint: asString(
        data['recipientHint'] ?? data['detectedRecipientHint'],
      ),
      upiIdHint: asString(data['upiIdHint'] ?? data['detectedUpiIdHint']),
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'eventId': id,
      'type': type,
      'status': _encodeStatus(status),
      'state': state,
      'appLabel': appLabel,
      'title': title,
      'body': body,
      'reason': reason,
      'amountHint': amountHint,
      'recipientHint': recipientHint,
      'upiIdHint': upiIdHint,
      'createdAt': createdAt.millisecondsSinceEpoch,
    };
  }

  Map<String, Object> toDbMap() {
    return <String, Object>{
      'id': id,
      'type': type,
      'payload': jsonEncode(toJson()),
      'created_at': createdAt.millisecondsSinceEpoch,
      'synced': synced ? 1 : 0,
    };
  }

  /// Shape used by the Firestore sink; child dashboards can read this
  /// collection directly when backend wiring exists.
  Map<String, Object?> toRemoteMap({
    required String familyId,
    required String deviceRole,
  }) {
    return <String, Object?>{
      'familyId': familyId,
      'deviceRole': deviceRole,
      'eventId': id,
      'type': type,
      'status': _encodeStatus(status),
      'state': state,
      'appLabel': appLabel,
      'title': title,
      'body': body,
      'reason': reason,
      'amountHint': amountHint,
      'recipientHint': recipientHint,
      'upiIdHint': upiIdHint,
      'createdAt': createdAt,
      'createdAtMs': createdAt.millisecondsSinceEpoch,
      'syncedAtMs': synced ? DateTime.now().millisecondsSinceEpoch : null,
    };
  }
}
